version: '3'
services:
    server:
        build: .
        entrypoint: /bin/blazetunnel
        command: server --domain meddler.xyz  -i 3600
        ports: 
            -   443:443
            -   2723:2723


    client:
        build: .
        entrypoint: /bin/blazetunnel
        command: client --tunnel "quic.meddler.xyz:2723" --local "localhost:4200" -i 3600
        ports: 
            -   4200:4200

