version: '3'
services:
    server:
        build: .
        entrypoint: /bin/blazetunnel
        command: server --domain meddler.xyz  -i 3600
        ports: 
            -   443:443/tcp
            -   2723:2723/udp


    client:
        build: .
        entrypoint: /bin/blazetunnel
        command: client --tunnel "quic.meddler.xyz:2723" --local "localhost:3001" -i 3600
        ports: 
            -   3001:3001/tcp
            -   2723:2723/udp


