version: "3"

services:
    server:
        build: .
        entrypoint: /bin/blazetunnel
        command: server --domain ${DOMAIN_NAME}  -i 3600
        env_file:
            - .env
        ports:
            - 443:443/tcp
            - 2723:2723/udp

    client:
        build: .
        entrypoint: /bin/blazetunnel
        command: client --tunnel "${SERVICE_NAME}.${DOMAIN_NAME}:2723" --local "mockserver:8000" -i 3600
        env_file:
            - .env
        ports:
            - 3001:3001/tcp
            - 2723:2723/udp
        depends_on:
            - mockserver


    prodclient:
        build: https://github.com/rounak316/blazetunnel.git
        entrypoint: /bin/blazetunnel
        command: client --tunnel "${SERVICE_NAME}.${DOMAIN_NAME}:2723" --local "mockserver:8000" -i 3600
        env_file:
            - .env
        ports:
            - 3001:3001/tcp
            - 2723:2723/udp
        depends_on:
            - mockserver

    mockserver:
        image: opensecurity/mobile-security-framework-mobsf
        expose:
            - 8000